# Generated by Django 3.2.4 on 2021-06-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinjambuku',
            name='body',
        ),
        migrations.RemoveField(
            model_name='pinjambuku',
            name='kode_buku',
        ),
        migrations.DeleteModel(
            name='Buku',
        ),
    ]
