# Generated by Django 3.2.4 on 2021-06-20 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_pinjambuku_kode_buku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinjambuku',
            name='kode_buku',
        ),
        migrations.AddField(
            model_name='pinjambuku',
            name='kd_buku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.buku'),
        ),
    ]
