# Generated by Django 3.2.4 on 2021-06-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210620_2312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PinjamBuku',
        ),
    ]
